### ISSUE TITLE
code golf question

### ISSUE THREAD

**Issue by glthomas** [primo-ppcg/BF-Crunch#2]
Hi @primo-ppcg , there is no issue pertaining to this repo, but rather I'm using this issue tracker to establish contact with you.  I've been working hard on the C# 99 problem.  I'm making good progress but have run out of ideas.  Was hoping you could mentor me as to what concepts I might need to further explore to get down to 211.  Would you be willing to reach out to me at my personal email gerald lee thomas at hot mail dot com

-Kind Regards

**Comment by glthomas** [comment]
@primo-ppcg Is there any chance we can discuss some things regarding code golf.  Kind Regards

**Comment by glthomas** [comment]
@primo-ppcg I could really use your help.  Will you kindly respond?

**Comment by primo-ppcg** [comment]
Sorry, I've had a number of personal matters to attend to recently. Drop me a message on Discord: primo#2898.
